import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

class Info {
  static List<String> title = [
    'Anticoagulation Clinics',
    'Bariatric Program',
    'Behavioral Health',
    'Breast Health Services',
    'Cancer Care',
    'Clinical Trials & Research',
    'Community Specialty Clinic',
    'Concierge Services',
    'Diabetes',
    'Employee Assistance Program',
    'HealthLine Physician Referral',
    'Heart & Vascular Services',
    'Heart Failure Centre',
    'Home Care',
    'Hyperbaric Medicine',
    'Infusion Therapy',
    'Laboratory Services',
    'Memory Disorders',
    'Minimally Invasive Surgery',
    'Neurological Care',
    'Orthopedics',
    'Pain Management',
    'Patient Financial Services',
    'Pregnancy and Newborns',
    'Radiology/Imaging Services',
    'Respiratory Care',
    'Robotic Surgery',
    'Sleep Disorders',
    'Support Group Listings',
    'Transfer Center',
    'Visitor Food Services',
    'Wound Care',
  ];
  static List<String> image = [
    'assets/images/i1.jpeg',
    'assets/images/i2.jpeg',
    'assets/images/i3.jpeg',
    'assets/images/i4.jpeg',
    'assets/images/i5.jpeg',
    'assets/images/i6.jpeg',
    'assets/images/i7.jpeg',
    'assets/images/i8.jpeg',
    'assets/images/i9.jpeg',
    'assets/images/i10.jpeg',
    'assets/images/i11.jpeg',
    'assets/images/i12.jpeg',
    'assets/images/i13.jpeg',
    'assets/images/i14.jpeg',
    'assets/images/i15.jpeg',
    'assets/images/i16.jpeg',
    'assets/images/i17.jpeg',
    'assets/images/i18.jpeg',
    'assets/images/i19.jpeg',
    'assets/images/i20.jpeg',
    'assets/images/i21.jpeg',
    'assets/images/i22.jpeg',
    'assets/images/i23.jpeg',
    'assets/images/i24.jpeg',
    'assets/images/i25.jpeg',
    'assets/images/i26.jpeg',
    'assets/images/i27.jpeg',
    'assets/images/i28.jpeg',
    'assets/images/i29.jpeg',
    'assets/images/i30.jpeg',
    'assets/images/i31.jpeg',
    'assets/images/i32.jpeg',
  ];
  static List<String> description = [
    'Our outpatient clinics help patients at any stage of anticoagulation therapy safely manage their blood thinner medications, including warfarin sodium, Coumadin and Jantoven, and increase the amount of time their blood tests remain in the appropriate range. We help you manage conditions that require the use of short-term or long-term anticoagulants, including atrial fibrillation, mechanical heart valves, deep vein thrombosis, pulmonary embolism or other forms of blood clots.',
    'Led by Medical Director Dr. Arundathi Rao, the Sarasota Memorial Bariatric and Metabolic Health Center provides a comprehensive program to help patients lose weight safely and resolve many of the health conditions associated with obesity, including Type 2 diabetes, heart disease, high blood pressure, sleep apnea and lipid disorders like high cholesterol or triglycerides. In addition to offering the latest technologies in weight-loss surgery and the best surgical expertise in the region, our knowledgeable and experienced team guides program participants during every step of their journey toward better health. We offer pre-surgery counseling as well as long-term follow-up care and support to ensure the best outcome and lasting weight-loss results. Bariatric surgery is a proven prescription for treating morbid obesity, but it isn?t for everyone. For those who do not qualify for bariatric surgery, or who decide against it, the Sarasota Memorial Bariatric and Metabolic Health Center provides a full slate of non-surgical, weight-loss options and support programs.',
    'If you or someone you care about is suffering from depression, anxiety, substance abuse or other mental health needs, we can help. Sarasota Memorial Hospital\'s Bayside Center for Behavioral Health offers timely, accessible mental health assessments, as well as referrals to the most appropriate level of care, so you or your loved one can get back to living a full life. Bayside Center is licensed by the Department of Children and Family Services, accredited by the Joint Commission, and approved by Medicare and Medicaid.',
    'When it comes to preventing breast cancer, the best defense is early detection. We ensure patients receive the most advanced care available to diagnose and treat cancer at its earliest and most curable stages.',
    'Whether it\'s genetic testing to learn about your risk factors, advanced imaging to detect tumors at their earliest stages, innovative surgical tools to remove difficult cancers, or access to advanced research afforded by our Cancer Research team, Sarasota Memorial provides a level of care and support found only at the nation\'s best cancer centers. We also provide an integrated supportive care program just for cancer patients, to help you during and after treatment. And for visitors to Sarasota, we can coordinate care with your hometown physician during your stay.',
    'Sarasota Memorial Hospital\'s Cancer Research department gives patients access to the latest global innovations in cancer research, with the benefit of being treated in their own community. Our local clinical trials are part of large-scale research studies that involve thousands of other patients in research centers across the nation. \n\nOur certified Cancer Research staff is specially trained to deliver safe patient care while educating and supporting their clinical-trial patients. Sarasota Memorial\'s Institutional Review Board and the U.S. National Institutes of Health review all clinical trials to ensure safe and ethical research standards are followed.',
    'Sarasota Memorial\'s Community Specialty Clinic (CSC) provides specialty medical care and referral services to Sarasota County residents who are uninsured or underinsured, who demonstrate a true financial need, and who are age 18 or older. Thanks to a \$275,000 expansion (completion expected fall 2017), the clinic now can accommodate more patients than it ever has in its 25 years of serving the local community. \n\nStaffed by volunteer physicians who treat CSC patients at the clinic or their own practices, the Community Specialty Clinic offers specialty medical care for many health problems and can arrange patient referrals to specialty services it does not offer. The CSC does not provide primary medical care, and patients must have a physician referral in order to be treated through the CSC.',
    'Sarasota Memorial is dedicated to providing all patients the ultimate level of care and customer service. To ensure that your experience at SMH is personalized and seamless from the start, we offer concierge services by physician referral and an enhanced communication process.',
    'Over 20 million Americans have diabetes, but one out of three doesn\'t know it. Diabetes is a silent disease. By the time it is diagnosed, damage to arteries, eyes, nerves and kidneys may have been going on for years. Through education and counseling, Sarasota Memorial\'s Diabetes Treatment Services will help you design a self-care program that can decrease your risk of developing complications related to diabetes.',
    'Everyone needs help from time to time sorting through difficult problems at work or at home. Whether they revolve around marriage and family, drugs or alcohol, financial or legal issues, or other personal matters, Sarasota Memorial\'s EAP counselors are here to help. Your personal EAP counselor is trained to help you with problems and to offer direction and alternatives through confidential counseling.',
    'Sarasota Memorial\'s HealthLine staff offer patients, visitors, physicians and staff access to the latest health and hospital programs available, including:\nFind A Physician\nListing of Medical Staff\nPhysician Referral Service\nReferral Services and Appointment Setting\nClass Information and Registration\nSupport Groups Information\nPrograms/Services provided by SMH\nProvide health information and resources on health topics\n\nIf you have difficulty obtaining health care services, Sarasota Memorial HealthLine can help with this, as well. Knowledgeable staff will guide you to the appropriate area or service.',
    'Sarasota Memorial offers the most comprehensive and advanced cardiovascular services in the region. Our cardiac team has decades of experience evaluating and treating irregular heartbeat, heart attack, heart failure, heart surgery, valve disorders, and other cardiovascular and thoracic disorders. Collectively, our nationally recognized physician team performs nearly 1,000 cardiovascular surgeries and more than 5,000 procedures every year.',
    'With more than 50 cardiologists on staff, Sarasota Memorial Hospital (SMH) offers patients the region\'s most comprehensive and advanced cardiovascular services. But what does that mean for our patients with heart failure?\n\nIt means care at SMH will exceed your expectations.',
    'Sarasota Memorial Home Care, facilitated by BayCare Health System, offers a full range of skilled nursing care, rehabilitation therapy and personal care for patients recovering at home from an operation, illness, injury or medical condition.',
    'Expert Care for Hard-to-Heal Wounds Sarasota Memorial\'s Center for Wound Healing combines advanced therapies, proven medical techniques and individual consultations to heal wounds that have resisted treatment for weeks, months and even years. We specialize in all hard-to-heal wounds, including:\nTraumatic wounds\nNon-healing surgical wounds\nArterial ulcers\nDiabetic foot ulcers\nChronic leg ulcers\nPressure ulcers (decubitus, bed sores)\nChronic osteomyelitis (bone infection)\nRadiation-related tissue damage',
    'If you\'re battling cancer, Crohn\'s disease or other serious illness that requires regular treatments, you\'ll find Sarasota Memorial Infusion a comfortable, pleasant and highly professional environment in which to receive care. Our patient bays are bright, with televisions and wireless Internet available so you can pass the time during treatment.',
    'Trust Sarasota Memorial Laboratory Services for high-quality, cost-effective testing. Our phlebotomists are specially trained and certified to perform your tests with technical precision, attention to detail and professionalism. Our board-certified pathologists and medical technologists ensure the integrity of every test, and deliver rapid results to physicians and providers.',
    'Do you or a family member have difficulty remembering new things, handling complicated tasks, solving everyday problems or finding the right words? Some memory loss is normal as we age, but if memory loss is affecting your life, Sarasota Memorial?s Memory Clinic can help. Partially funded by the Florida Department of Elder Affairs, the clinic provides assessment and evaluation by a multi-disciplinary team of Neurologists, Geriatricians and Neuropsychologists.',
    'Minimally invasive tools and techniques allow surgeons to perform a wide array of surgeries through small, keyhole-size incisions. The surgical site typically requires only a stitch or two to close, versus larger incisions required by open surgery, and typically result in shorter hospital stays and quicker return to normal activities. \n\nOur minimally invasive surgery team comprises more than 200 general and specialty surgeons - the largest and most experienced in the region - offering multidisciplinary expertise that ranges from cardiothoracic surgery to urological, gynecological and surgical cancer procedures.',
    'The Sarasota Memorial Neuroscience Center of Excellence brings together a unique team of specialists and sub-specialists to evaluate and provide the most effective care for patients affected by neurological conditions of the brain, spinal cord, peripheral nerves and muscles.\n\nOur multi-disciplinary team comprises physician specialists with in-depth subspecialty expertise, including neurologists, neurosurgeons, neuroradiologists, otolaryngologists (ear, nose and throat specialists), endocrinologists, radiation oncologists, physiatrists, intensive care specialists, emergency medicine physicians, specialists in geriatric and psychiatric medicine, experienced nurses, nurse practitioners, physician assistants and neuro-rehabilitation specialists.',
    'Whether your joint, spine or other orthopedic problems stem from trauma, injury, illness or simply aging, Sarasota Memorial\'s comprehensive Orthopedic Services program aims to get you back to living a pain free, active life.',
    'Our expert Pain Medicine team offers the region\'s widest array of coordinated pain care services, helping our patients with relief from chronic conditions such as: \n\n\nArthritis\nBack and neck pain (including spinal stenosis and degenerative disc disease)\nCancer pain\nComplex regional pain syndrome\nDiabetic neuropathy\nFibromyalgia\nFoot pain\nHeadaches and migraines\nLower back pain\nNeuropathic pain\nPostherpetic neuralgia (shingles)\nSciatica\nShoulder pain\nSpasticity\nPain from spinal cord injuries, stroke, multiple sclerosis and other neurologic conditions\nAuto accident injuries\nWork-related injuries',
    'Sarasota Memorial is committed to transparency and providing our patients with the information they need to make health care decisions. Our Patient Financial Services department provides patients and third-party insurance carriers with timely and accurate billings. We also ensure that each patient understands his or her financial responsibility for medical services, and help with financial aid options when needed.',
    'From the most routine births to the most complex, no other hospital in southwest Florida is as equipped to help you deliver a healthy baby (or multiples) in the most natural and safest way possible. Sarasota Memorial is nationally recognized for its high-quality OB/GYN services, high-risk pregnancy care and Level III Neonatal Intensive Care Unit for critically ill newborns and premature babies.',
    'Sarasota Memorial and its network of nine neighborhood care centers offer a full spectrum of digital imaging and radiology services. From highly specialized technologists and Radiology Nurses to board-certified Radiologists, we offer the best screening, diagnostic and treatment options, scheduled within 24 hours with fast, accurate results. All of Sarasota Memorial\'s radiology and imaging centers are fully accredited by the American College of Radiology.',
    'Sarasota Memorial?s multi-disciplinary respiratory care team provides a full spectrum of diagnostic and therapeutic services for patients with lung disease, injuries and breathing disorders.',
    'Minimally invasive tools and techniques allow surgeons to perform a wide array of surgeries through small, keyhole-size incisions. The surgical site typically requires only a stitch or two to close, versus larger incisions required by open surgery, and typically result in shorter hospital stays and quicker return to normal activities.',
    'Sarasota Memorial\'s Sleep Disorders Center is an outpatient facility equipped to evaluate and treat people suffering from sleep apnea and other sleep-related problems.Established in 1992, the center has consistently been awarded the nation\'s highest level of accreditation by the American Academy of Sleep Medicine.',
    'The following support groups are held at Sarasota Memorial or facilitated by Sarasota Memorial staff members at other local locations. Please call the listed phone numbers for support-group meeting dates, times and locations. The Sarasota Memorial HealthLine can help you register for classes and programs sponsored by the hospital.\n\nContact HealthLine via LiveChat online or phone at 941-917-7777, or visit the Community Health Calendar for more information. HealthLine is open Monday through Friday, from 8:30 a.m. to 5 p.m., major holidays excluded.',
    'The Sarasota Memorial Transfer Center helps ensure the quick and smooth transfer of patients from other hospitals to Sarasota Memorial. Just one call to (941) 917-3900 initiates the transfer process. Specially trained registered nurses are available 24/7 to:Facilitate physician-to-physician consultation.Arrange for prompt placement of patient on the appropriate specialty care unit at Sarasota Memorial.',
    'Windows Cafe?\nLocated on the fourth floor of the hospital, near the B elevators, Windows Cafe? is a self-service-style cafe?, offering a variety of entrees and sides, a full salad bar and a featured made-to-order Chef Station. For those in a hurry, there are also Grab and Go items, along with various snacks, desserts and a large selection of beverages. Windows features a Fuel Up for Wellness program, which showcases premium healthy selections. On Mondays, it offers "Meatless Selections;" Wednesday is the popular "RD Choice" day; and Friday rounds out the work week with "Fryer-less Friday" options. Eating healthy never tasted so good! Hours: Monday - Friday, 6 a.m. to 3 p.m.; Saturday - Sunday, 6 a.m. to 3 p.m.\n\n1700 South Caf?\nWant to relax without having to leave the hospital campus? 1700 South Caf? is the perfect escape to a warm, friendly atmosphere with inviting music, delicious food selections and a full line of Starbucks Coffee! Join us for homemade pastries, Grab and Go selections and homemade salads and sandwiches. The caf? is located on the first floor of the hospital, near the D elevators, with easy access to the tables and chairs in the open air courtyard. Open Monday - Friday, 7 a.m. to 2 a.m., Saturday and Sunday, 2 p.m. to 2 a.m.\n\nCourtyard Caf?\nLocated in the first floor Courtyard Tower lobby, just inside the hospital\'s main entrance and adjacent to the open air courtyard, the caf? features Starbucks Coffee, including specialty hot and cold selections, fresh baked pastries and a variety of sandwiches and snacks perfect for any taste. In addition, we feature Dilmah tea, a specialty product from Sri Lanka. Open Monday?- Friday, 6:30 a.m. to 3:00 p.m.\n\nVISA/Master Card/Discover and American Express accepted at Windows Cafeteria, 1700 South Caf? and Courtyard Caf?.\n\nVending Machines Vending machines are located on the first floor: near the D and G elevators and Courtyard Tower.',
    'Expert Care for Hard-to-Heal Wounds Sarasota Memorial\'s Center for Wound Healing combines advanced therapies, proven medical techniques and individual consultations to heal wounds that have resisted treatment for weeks, months and even years. We specialize in all hard-to-heal wounds, including: Traumatic wounds Non-healing surgical wounds Arterial ulcers Diabetic foot ulcers Chronic leg ulcers Pressure ulcers (decubitus, bed sores) Chronic osteomyelitis (bone infection) Radiation-related tissue damage',
  ];

  static List<String> url = [
    'https://www.smh.com/Home/Services/Anticoagulation',
    'https://www.smh.com/Bariatric',
    'https://www.smh.com/Home/Services/Behavioral-Health',
    'https://www.smh.com/Home/Services/Womens-Health-Services',
    'https://www.smh.com/Home/Services/Cancer-Institute',
    'https://www.smh.com/Home/Services/Clinical-Trials',
    'https://www.smh.com/communityspecialtyclinic',
    'https://www.smh.com/Home/Patients-Visitors/Concierge-Services',
    'https://www.smh.com/Home/Services/Diabetes',
    'https://www.smh.com/For-Employees/Employee-Assistance-Program',
    'https://www.smh.com/Healthline',
    'https://www.smh.com/Home/Services/Heart-Vascular-Services',
    'https://www.smh.com/heart-failure',
    'https://www.smh.com/Home/Services/Home-Care',
    'https://www.smh.com/Home/Services/Hyperbaric-Medicine',
    'https://www.smh.com/Home/Services/Infusion-Therapy',
    'https://www.smh.com/lab',
    'https://www.smh.com/Home/Services/Memory-Disorders',
    'https://www.smh.com/Home/Services/Surgery/Minimally-Invasive-Robotic-Surgery',
    'https://www.smh.com/Home/Services/Neurological-Care',
    'https://www.smh.com/Home/Services/Orthopedics',
    'https://www.smh.com/paincare',
    'https://www.smh.com/Home/Patients-Visitors/Patient-Financial-Services',
    'https://www.smh.com/Home/Services/Maternity-Services',
    'https://www.smh.com/diagnostics',
    'https://www.smh.com/Home/Services/Respiratory-Care',
    'https://www.smh.com/Home/Services/Surgery/Minimally-Invasive-Robotic-Surgery',
    'https://www.smh.com/Home/Services/Sleep-Disorders',
    'https://www.smh.com/Contact-Us/Support-Group-Listings',
    'https://www.smh.com/Home/Patients-Visitors/Transfer-Center',
    'https://www.smh.com/Home/Patients-Visitors/Visitor-Food-Services',
    'https://www.smh.com/Home/Services/Wound-Care',
  ];
}
